[Описание задачи](https://cups.online/ru/training/8/tasks/1367)

# Установка зависимостей

In [ ]:
!pip install implicit

Collecting implicit
  Downloading implicit-0.7.2.tar.gz (70 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.3/70.3 kB 3.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from implicit) (2.0.2)
Requirement already satisfied: scipy>=0.16 in /usr/local/lib/python3.12/dist-packages (from implicit) (1.16.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from implicit) (4.67.3)
Requirement already satisfied: threadpoolctl in /usr/local/lib/python3.12/dist-packages (from implicit) (3.6.0)
Building wheels for collected packages: implicit
  Building wheel for implicit (pyproject.toml) ... done
  Created wheel for implicit: filename=implicit-0.7.2-cp312-cp312-linux_x86_64.whl size=933264 sha256=2693dd2a0c70da3882549b878ef3ca79409647abb8aeb241fc40e212ab0d5813
  Stored in directory: /root/.cache/pip/wheels/b2/00/4f/9ff8af07a0a53ac6007ea5d739da19cfe147a2df542b6899f8
Successfully built implicit
Installing collected packages: implicit
Successfully installed implicit-0.7.2

# Импорты

In [ ]:
import pandas as pd
import numpy as np
from scipy.sparse import coo_matrix, csr_matrix

# Работа с данными

In [ ]:
df = pd.read_csv('train.csv')
df.head(5)

   user_id  course_id
0    39972         34
1    56815         51
2    63734         20
3    17896         81
4    36961         64

In [ ]:
df.shape

(10272, 2)

In [ ]:
print(df['user_id'].nunique(), df['course_id'].nunique())

4862 171

Почистим пользователей и курсы с количеством взаимодействий, меньше 2

In [ ]:
from copy import deepcopy, copy

def filter_column(df, min_freq):
    df = deepcopy(df)
    for col in df.columns:
        grouped = df.groupby(col).agg(
            freq=(col, 'count')
        ).reset_index()
        grouped_filtered = grouped[grouped['freq'] >= min_freq]
        df = df.loc[df[col].isin(grouped_filtered[col])]

    return df

def filter_dataframe(df, cols, min_freq):

    df_to_filter = df[cols].copy()

    while True:
        start_len = df_to_filter.shape[0]

        df_to_filter = filter_column(df_to_filter, min_freq)

        if df_to_filter.shape[0] == start_len:
            break

    for col in df_to_filter.columns:
        df = df.loc[df[col].isin(df_to_filter[col])]

    return df

In [ ]:
df_filtered = filter_dataframe(df, ['user_id', 'course_id'], 4)
df_filtered.shape

(3944, 2)

In [ ]:
df_filtered.head(5)

    user_id  course_id
3     17896         81
4     36961         64
8     68308         13
9     62349        134
10    11072         10

Узнаем, какие топ-3 курса являются самыми популярным, чтобы рекомендовать их новым холодным пользователям

In [ ]:
most_popular = df_filtered['course_id'].value_counts()
most_popular

course_id
7      190
1      171
15     169
51     128
43     123
      ...
166      5
221      4
196      4
237      4
87       4
Name: count, Length: 128, dtype: int64

In [ ]:
most_popular_courses_id = [7, 1, 15]

Кодирование пользователей и курсов

In [ ]:
user2idx = {u: i for i, u in enumerate(df_filtered['user_id'].unique())}
course2idx = {item: i for i, item in enumerate(df_filtered['course_id'].unique())}

idx2user = {i: u for u, i in user2idx.items()}
idx2course = {i: item for item, i in course2idx.items()}

In [ ]:
most_popular_courses_id = [course2idx[course_id] for course_id in most_popular_courses_id]
most_popular_courses_id

[34, 17, 40]

In [ ]:
df_filtered['user_idx'] = df_filtered['user_id'].map(user2idx)
df_filtered['course_idx'] = df_filtered['course_id'].map(course2idx)

Построение разреженной матрицы интеракций

In [ ]:
n_users = df_filtered['user_idx'].nunique()
n_courses = df_filtered['course_idx'].nunique()
n_interactions = df_filtered.shape[0]

interactions = csr_matrix(
    (
        np.ones(n_interactions),
        (df_filtered['user_idx'], df_filtered['course_idx'])
    ),
    shape=(n_users, n_courses)
)

In [ ]:
interactions.shape

(667, 128)

In [ ]:
from implicit.evaluation import leave_k_out_split

train, test = leave_k_out_split(
    interactions,
    K=1
)

In [ ]:
from implicit.nearest_neighbours import bm25_weight

train_bm25 = bm25_weight(train).tocsr()

# Модель и подбор гиперпараметров

Проинициализируем метрики для валидации модели и подбора гиперпараметров.

In [ ]:
from typing import List, Optional

def ap_metric(
    gt_items: List[int],
    predictions: List[int],
    topk: Optional[int]=None
):
    gt_items = np.asarray(gt_items)
    predictions = np.asarray(predictions)

    if len(gt_items) == 0:
        return 0.0

    if topk is not None:
        predictions = predictions[:topk]
        k = min(topk, len(gt_items))
    else:
        k = len(gt_items)

    relevance = np.isin(predictions, gt_items).astype(int)
    cumsum = np.cumsum(relevance)

    precision = cumsum / np.arange(1, len(relevance) + 1)

    ap = (1 / k) * np.sum(relevance * precision)

    return ap


def map_metric(
    gt_items_list: List[List[int]],
    predictions_list: List[List[int]],
    topk: Optional[int] = None
) -> float:

    if not gt_items_list or not predictions_list:
        return 0.0

    if len(gt_items_list) != len(predictions_list):
        raise ValueError("Количество пользователей в gt и predictions должно совпадать")

    ap_scores = []
    for gt, pred in zip(gt_items_list, predictions_list):
        ap = ap_metric(gt, pred, topk)
        ap_scores.append(ap)

    return np.mean(ap_scores) if ap_scores else 0.0

def hr_metric(
    gt_items: List[int],
    predictions: List[int],
    topk: Optional[int]=None
):

    if len(gt_items) == 0:
        return 0

    if topk is not None:
        predictions = predictions[:topk]

    relevance = np.isin(predictions, gt_items).astype(int)

    if np.sum(relevance) > 0:
        return 1
    return 0

Baseline MostPopular

In [ ]:
from collections import Counter

K = 3

item_popularity = np.asarray(train.sum(axis=0)).ravel()
popular_items = np.argsort(-item_popularity)

test_users = np.where(test.getnnz(axis=1) > 0)[0]

predictions_list = []
gt_items_list = []

for u in test_users:
    seen = set(train[u].indices)
    pred = [item for item in popular_items if item not in seen][:K]
    gt = test[u].indices.tolist()

    predictions_list.append(pred)
    gt_items_list.append(gt)

hr_scores = [hr_metric(gt, pred, topk=K) for gt, pred in zip(gt_items_list, predictions_list)]
ap_scores = [ap_metric(gt, pred, topk=K) for gt, pred in zip(gt_items_list, predictions_list)]

print(f"Popularity HR@{K} = {np.mean(hr_scores):.4f}")
print(f"Popularity MAP@{K} = {np.mean(ap_scores):.4f}")

Popularity HR@3 = 0.1700
Popularity MAP@3 = 0.1090

Подбор гиперпараметров

In [ ]:
from tqdm import tqdm
from itertools import product
from implicit.cpu.als import AlternatingLeastSquares
import pandas as pd
import numpy as np

factors_grid = [16, 32]
alpha_grid = [1, 5, 10]
reg_grid = [0.01, 0.05, 0.1, 0.5]
iter_grid = [10, 20, 30, 40]

K = 3
results = []

test_users = np.where(test.getnnz(axis=1) > 0)[0]

for f, a, it, r in tqdm(list(product(factors_grid, alpha_grid, iter_grid, reg_grid))):
    model = AlternatingLeastSquares(
        factors=f,
        regularization=r,
        alpha=a,
        iterations=it,
        random_state=42
    )

    model.fit(train_bm25)

    rec_items, _ = model.recommend(
        userid=test_users,
        user_items=train_bm25[test_users],
        N=3,
        filter_already_liked_items=True
    )

    if len(test_users) == 1:
        rec_items = np.expand_dims(rec_items, axis=0)

    predictions_list = rec_items.tolist()

    gt_items_list = [test[u].indices.tolist() for u in test_users]

    hr_scores = []
    ap_scores = []

    for gt, pred in zip(gt_items_list, predictions_list):
        hr_scores.append(hr_metric(gt, pred, topk=K))
        ap_scores.append(ap_metric(gt, pred, topk=K))

    hr_k = np.mean(hr_scores)
    map_k = np.mean(ap_scores)

    results.append({
        'factors': f,
        'alpha': a,
        'reg': r,
        'iterations': it,
        f'HR@{K}': hr_k,
        f'MAP@{K}': map_k
    })

    print(
        f"factors={f}, alpha={a}, iterations={it}, reg={r} | "
        f"HR@{K}={hr_k:.4f}, MAP@{K}={map_k:.4f}"
    )

results_df = pd.DataFrame(results).sort_values(
    by=[f'MAP@{K}', f'HR@{K}'],
    ascending=False
).reset_index(drop=True)

print("\nЛучшие гиперпараметры:")
print(results_df.head(10))

  0%|          | 0/96 [00:00<?, ?it/s]

  0%|          | 0/10 [00:00<?, ?it/s]

  1%|          | 1/96 [00:00<00:40,  2.35it/s]

factors=16, alpha=1, iterations=10, reg=0.01 | HR@3=0.2534, MAP@3=0.1870

  0%|          | 0/10 [00:00<?, ?it/s]

  2%|▏         | 2/96 [00:00<00:40,  2.35it/s]

factors=16, alpha=1, iterations=10, reg=0.05 | HR@3=0.2525, MAP@3=0.1862

  0%|          | 0/10 [00:00<?, ?it/s]

  3%|▎         | 3/96 [00:01<00:39,  2.37it/s]

factors=16, alpha=1, iterations=10, reg=0.1 | HR@3=0.2542, MAP@3=0.1881

  0%|          | 0/10 [00:00<?, ?it/s]

  4%|▍         | 4/96 [00:01<00:39,  2.34it/s]

factors=16, alpha=1, iterations=10, reg=0.5 | HR@3=0.2508, MAP@3=0.1887

  0%|          | 0/20 [00:00<?, ?it/s]

  5%|▌         | 5/96 [00:02<00:40,  2.22it/s]

factors=16, alpha=1, iterations=20, reg=0.01 | HR@3=0.2508, MAP@3=0.1884

  0%|          | 0/20 [00:00<?, ?it/s]

  6%|▋         | 6/96 [00:02<00:42,  2.14it/s]

factors=16, alpha=1, iterations=20, reg=0.05 | HR@3=0.2458, MAP@3=0.1860

  0%|          | 0/20 [00:00<?, ?it/s]

  7%|▋         | 7/96 [00:03<00:42,  2.09it/s]

factors=16, alpha=1, iterations=20, reg=0.1 | HR@3=0.2475, MAP@3=0.1859

  0%|          | 0/20 [00:00<?, ?it/s]

  8%|▊         | 8/96 [00:03<00:42,  2.05it/s]

factors=16, alpha=1, iterations=20, reg=0.5 | HR@3=0.2517, MAP@3=0.1880

  0%|          | 0/30 [00:00<?, ?it/s]

  9%|▉         | 9/96 [00:04<00:44,  1.96it/s]

factors=16, alpha=1, iterations=30, reg=0.01 | HR@3=0.2593, MAP@3=0.1901

  0%|          | 0/30 [00:00<?, ?it/s]

 10%|█         | 10/96 [00:04<00:45,  1.90it/s]

factors=16, alpha=1, iterations=30, reg=0.05 | HR@3=0.2551, MAP@3=0.1909

  0%|          | 0/30 [00:00<?, ?it/s]

 11%|█▏        | 11/96 [00:05<00:45,  1.87it/s]

factors=16, alpha=1, iterations=30, reg=0.1 | HR@3=0.2542, MAP@3=0.1904

  0%|          | 0/30 [00:00<?, ?it/s]

 12%|█▎        | 12/96 [00:05<00:45,  1.83it/s]

factors=16, alpha=1, iterations=30, reg=0.5 | HR@3=0.2576, MAP@3=0.1893

  0%|          | 0/40 [00:00<?, ?it/s]

 14%|█▎        | 13/96 [00:06<00:48,  1.73it/s]

factors=16, alpha=1, iterations=40, reg=0.01 | HR@3=0.2559, MAP@3=0.1881

  0%|          | 0/40 [00:00<?, ?it/s]

 15%|█▍        | 14/96 [00:07<00:51,  1.59it/s]

factors=16, alpha=1, iterations=40, reg=0.05 | HR@3=0.2551, MAP@3=0.1877

  0%|          | 0/40 [00:00<?, ?it/s]

 16%|█▌        | 15/96 [00:08<01:02,  1.29it/s]

factors=16, alpha=1, iterations=40, reg=0.1 | HR@3=0.2551, MAP@3=0.1886

  0%|          | 0/40 [00:00<?, ?it/s]

 17%|█▋        | 16/96 [00:09<01:17,  1.03it/s]

factors=16, alpha=1, iterations=40, reg=0.5 | HR@3=0.2517, MAP@3=0.1855

  0%|          | 0/10 [00:00<?, ?it/s]

 18%|█▊        | 17/96 [00:10<01:09,  1.14it/s]

factors=16, alpha=5, iterations=10, reg=0.01 | HR@3=0.2483, MAP@3=0.1808

  0%|          | 0/10 [00:00<?, ?it/s]

 19%|█▉        | 18/96 [00:10<00:58,  1.33it/s]

factors=16, alpha=5, iterations=10, reg=0.05 | HR@3=0.2433, MAP@3=0.1801

  0%|          | 0/10 [00:00<?, ?it/s]

 20%|█▉        | 19/96 [00:11<00:49,  1.54it/s]

factors=16, alpha=5, iterations=10, reg=0.1 | HR@3=0.2449, MAP@3=0.1806

  0%|          | 0/10 [00:00<?, ?it/s]

 21%|██        | 20/96 [00:11<00:43,  1.74it/s]

factors=16, alpha=5, iterations=10, reg=0.5 | HR@3=0.2399, MAP@3=0.1785

  0%|          | 0/20 [00:00<?, ?it/s]

 22%|██▏       | 21/96 [00:12<00:41,  1.79it/s]

factors=16, alpha=5, iterations=20, reg=0.01 | HR@3=0.2525, MAP@3=0.1864

  0%|          | 0/20 [00:00<?, ?it/s]

 23%|██▎       | 22/96 [00:12<00:38,  1.90it/s]

factors=16, alpha=5, iterations=20, reg=0.05 | HR@3=0.2534, MAP@3=0.1871

  0%|          | 0/20 [00:00<?, ?it/s]

 24%|██▍       | 23/96 [00:13<00:38,  1.90it/s]

factors=16, alpha=5, iterations=20, reg=0.1 | HR@3=0.2517, MAP@3=0.1849

  0%|          | 0/20 [00:00<?, ?it/s]

 25%|██▌       | 24/96 [00:13<00:37,  1.94it/s]

factors=16, alpha=5, iterations=20, reg=0.5 | HR@3=0.2525, MAP@3=0.1846

  0%|          | 0/30 [00:00<?, ?it/s]

 26%|██▌       | 25/96 [00:14<00:37,  1.87it/s]

factors=16, alpha=5, iterations=30, reg=0.01 | HR@3=0.2567, MAP@3=0.1873

  0%|          | 0/30 [00:00<?, ?it/s]

 27%|██▋       | 26/96 [00:14<00:38,  1.84it/s]

factors=16, alpha=5, iterations=30, reg=0.05 | HR@3=0.2542, MAP@3=0.1860

  0%|          | 0/30 [00:00<?, ?it/s]

 28%|██▊       | 27/96 [00:15<00:37,  1.82it/s]

factors=16, alpha=5, iterations=30, reg=0.1 | HR@3=0.2542, MAP@3=0.1846

  0%|          | 0/30 [00:00<?, ?it/s]

 29%|██▉       | 28/96 [00:16<00:39,  1.74it/s]

factors=16, alpha=5, iterations=30, reg=0.5 | HR@3=0.2525, MAP@3=0.1846

  0%|          | 0/40 [00:00<?, ?it/s]

 30%|███       | 29/96 [00:16<00:40,  1.65it/s]

factors=16, alpha=5, iterations=40, reg=0.01 | HR@3=0.2609, MAP@3=0.1856

  0%|          | 0/40 [00:00<?, ?it/s]

 31%|███▏      | 30/96 [00:17<00:41,  1.61it/s]

factors=16, alpha=5, iterations=40, reg=0.05 | HR@3=0.2567, MAP@3=0.1846

  0%|          | 0/40 [00:00<?, ?it/s]

 32%|███▏      | 31/96 [00:18<00:40,  1.59it/s]

factors=16, alpha=5, iterations=40, reg=0.1 | HR@3=0.2576, MAP@3=0.1853

  0%|          | 0/40 [00:00<?, ?it/s]

 33%|███▎      | 32/96 [00:18<00:43,  1.48it/s]

factors=16, alpha=5, iterations=40, reg=0.5 | HR@3=0.2567, MAP@3=0.1863

  0%|          | 0/10 [00:00<?, ?it/s]

 34%|███▍      | 33/96 [00:19<00:37,  1.67it/s]

factors=16, alpha=10, iterations=10, reg=0.01 | HR@3=0.2256, MAP@3=0.1686

  0%|          | 0/10 [00:00<?, ?it/s]

 35%|███▌      | 34/96 [00:19<00:34,  1.82it/s]

factors=16, alpha=10, iterations=10, reg=0.05 | HR@3=0.2273, MAP@3=0.1682

  0%|          | 0/10 [00:00<?, ?it/s]

 36%|███▋      | 35/96 [00:20<00:31,  1.92it/s]

factors=16, alpha=10, iterations=10, reg=0.1 | HR@3=0.2306, MAP@3=0.1703

  0%|          | 0/10 [00:00<?, ?it/s]

 38%|███▊      | 36/96 [00:20<00:30,  1.99it/s]

factors=16, alpha=10, iterations=10, reg=0.5 | HR@3=0.2365, MAP@3=0.1733

  0%|          | 0/20 [00:00<?, ?it/s]

 39%|███▊      | 37/96 [00:21<00:33,  1.76it/s]

factors=16, alpha=10, iterations=20, reg=0.01 | HR@3=0.2500, MAP@3=0.1811

  0%|          | 0/20 [00:00<?, ?it/s]

 40%|███▉      | 38/96 [00:22<00:40,  1.44it/s]

factors=16, alpha=10, iterations=20, reg=0.05 | HR@3=0.2542, MAP@3=0.1811

  0%|          | 0/20 [00:00<?, ?it/s]

 41%|████      | 39/96 [00:23<00:43,  1.30it/s]

factors=16, alpha=10, iterations=20, reg=0.1 | HR@3=0.2542, MAP@3=0.1824

  0%|          | 0/20 [00:00<?, ?it/s]

 42%|████▏     | 40/96 [00:24<00:42,  1.31it/s]

factors=16, alpha=10, iterations=20, reg=0.5 | HR@3=0.2542, MAP@3=0.1820

  0%|          | 0/30 [00:00<?, ?it/s]

 43%|████▎     | 41/96 [00:24<00:42,  1.30it/s]

factors=16, alpha=10, iterations=30, reg=0.01 | HR@3=0.2508, MAP@3=0.1834

  0%|          | 0/30 [00:00<?, ?it/s]

 44%|████▍     | 42/96 [00:25<00:38,  1.41it/s]

factors=16, alpha=10, iterations=30, reg=0.05 | HR@3=0.2525, MAP@3=0.1824

  0%|          | 0/30 [00:00<?, ?it/s]

 45%|████▍     | 43/96 [00:26<00:36,  1.47it/s]

factors=16, alpha=10, iterations=30, reg=0.1 | HR@3=0.2517, MAP@3=0.1810

  0%|          | 0/30 [00:00<?, ?it/s]

 46%|████▌     | 44/96 [00:26<00:33,  1.53it/s]

factors=16, alpha=10, iterations=30, reg=0.5 | HR@3=0.2551, MAP@3=0.1797

  0%|          | 0/40 [00:00<?, ?it/s]

 47%|████▋     | 45/96 [00:27<00:33,  1.50it/s]

factors=16, alpha=10, iterations=40, reg=0.01 | HR@3=0.2593, MAP@3=0.1842

  0%|          | 0/40 [00:00<?, ?it/s]

 48%|████▊     | 46/96 [00:27<00:33,  1.51it/s]

factors=16, alpha=10, iterations=40, reg=0.05 | HR@3=0.2567, MAP@3=0.1841

  0%|          | 0/40 [00:00<?, ?it/s]

 49%|████▉     | 47/96 [00:28<00:32,  1.49it/s]

factors=16, alpha=10, iterations=40, reg=0.1 | HR@3=0.2551, MAP@3=0.1827

  0%|          | 0/40 [00:00<?, ?it/s]

 50%|█████     | 48/96 [00:29<00:32,  1.49it/s]

factors=16, alpha=10, iterations=40, reg=0.5 | HR@3=0.2559, MAP@3=0.1821

  0%|          | 0/10 [00:00<?, ?it/s]

 51%|█████     | 49/96 [00:29<00:30,  1.56it/s]

factors=32, alpha=1, iterations=10, reg=0.01 | HR@3=0.1625, MAP@3=0.1146

  0%|          | 0/10 [00:00<?, ?it/s]

 52%|█████▏    | 50/96 [00:30<00:27,  1.65it/s]

factors=32, alpha=1, iterations=10, reg=0.05 | HR@3=0.1616, MAP@3=0.1148

  0%|          | 0/10 [00:00<?, ?it/s]

 53%|█████▎    | 51/96 [00:30<00:26,  1.73it/s]

factors=32, alpha=1, iterations=10, reg=0.1 | HR@3=0.1599, MAP@3=0.1143

  0%|          | 0/10 [00:00<?, ?it/s]

 54%|█████▍    | 52/96 [00:31<00:25,  1.74it/s]

factors=32, alpha=1, iterations=10, reg=0.5 | HR@3=0.1633, MAP@3=0.1173

  0%|          | 0/20 [00:00<?, ?it/s]

 55%|█████▌    | 53/96 [00:32<00:28,  1.51it/s]

factors=32, alpha=1, iterations=20, reg=0.01 | HR@3=0.1574, MAP@3=0.1178

  0%|          | 0/20 [00:00<?, ?it/s]

 56%|█████▋    | 54/96 [00:33<00:29,  1.44it/s]

factors=32, alpha=1, iterations=20, reg=0.05 | HR@3=0.1658, MAP@3=0.1195

  0%|          | 0/20 [00:00<?, ?it/s]

 57%|█████▋    | 55/96 [00:34<00:30,  1.33it/s]

factors=32, alpha=1, iterations=20, reg=0.1 | HR@3=0.1717, MAP@3=0.1218

  0%|          | 0/20 [00:00<?, ?it/s]

 58%|█████▊    | 56/96 [00:35<00:33,  1.21it/s]

factors=32, alpha=1, iterations=20, reg=0.5 | HR@3=0.1675, MAP@3=0.1197

  0%|          | 0/30 [00:00<?, ?it/s]

 59%|█████▉    | 57/96 [00:37<00:46,  1.20s/it]

factors=32, alpha=1, iterations=30, reg=0.01 | HR@3=0.1641, MAP@3=0.1211

  0%|          | 0/30 [00:00<?, ?it/s]

 60%|██████    | 58/96 [00:38<00:50,  1.33s/it]

factors=32, alpha=1, iterations=30, reg=0.05 | HR@3=0.1658, MAP@3=0.1199

  0%|          | 0/30 [00:00<?, ?it/s]

 61%|██████▏   | 59/96 [00:39<00:45,  1.24s/it]

factors=32, alpha=1, iterations=30, reg=0.1 | HR@3=0.1684, MAP@3=0.1194

  0%|          | 0/30 [00:00<?, ?it/s]

 62%|██████▎   | 60/96 [00:40<00:41,  1.14s/it]

factors=32, alpha=1, iterations=30, reg=0.5 | HR@3=0.1675, MAP@3=0.1223

  0%|          | 0/40 [00:00<?, ?it/s]

 64%|██████▎   | 61/96 [00:41<00:41,  1.18s/it]

factors=32, alpha=1, iterations=40, reg=0.01 | HR@3=0.1650, MAP@3=0.1202

  0%|          | 0/40 [00:00<?, ?it/s]

 65%|██████▍   | 62/96 [00:43<00:41,  1.23s/it]

factors=32, alpha=1, iterations=40, reg=0.05 | HR@3=0.1726, MAP@3=0.1230

  0%|          | 0/40 [00:00<?, ?it/s]

 66%|██████▌   | 63/96 [00:44<00:41,  1.24s/it]

factors=32, alpha=1, iterations=40, reg=0.1 | HR@3=0.1726, MAP@3=0.1208

  0%|          | 0/40 [00:00<?, ?it/s]

 67%|██████▋   | 64/96 [00:45<00:38,  1.19s/it]

factors=32, alpha=1, iterations=40, reg=0.5 | HR@3=0.1717, MAP@3=0.1219

  0%|          | 0/10 [00:00<?, ?it/s]

 68%|██████▊   | 65/96 [00:46<00:31,  1.01s/it]

factors=32, alpha=5, iterations=10, reg=0.01 | HR@3=0.1776, MAP@3=0.1298

  0%|          | 0/10 [00:00<?, ?it/s]

 69%|██████▉   | 66/96 [00:46<00:25,  1.16it/s]

factors=32, alpha=5, iterations=10, reg=0.05 | HR@3=0.1751, MAP@3=0.1278

  0%|          | 0/10 [00:00<?, ?it/s]

 70%|██████▉   | 67/96 [00:47<00:21,  1.33it/s]

factors=32, alpha=5, iterations=10, reg=0.1 | HR@3=0.1810, MAP@3=0.1312

  0%|          | 0/10 [00:00<?, ?it/s]

 71%|███████   | 68/96 [00:47<00:19,  1.46it/s]

factors=32, alpha=5, iterations=10, reg=0.5 | HR@3=0.1877, MAP@3=0.1329

  0%|          | 0/20 [00:00<?, ?it/s]

 72%|███████▏  | 69/96 [00:48<00:18,  1.43it/s]

factors=32, alpha=5, iterations=20, reg=0.01 | HR@3=0.1818, MAP@3=0.1341

  0%|          | 0/20 [00:00<?, ?it/s]

 73%|███████▎  | 70/96 [00:49<00:20,  1.29it/s]

factors=32, alpha=5, iterations=20, reg=0.05 | HR@3=0.1869, MAP@3=0.1369

  0%|          | 0/20 [00:00<?, ?it/s]

 74%|███████▍  | 71/96 [00:50<00:24,  1.04it/s]

factors=32, alpha=5, iterations=20, reg=0.1 | HR@3=0.1860, MAP@3=0.1372

  0%|          | 0/20 [00:00<?, ?it/s]

 75%|███████▌  | 72/96 [00:52<00:26,  1.12s/it]

factors=32, alpha=5, iterations=20, reg=0.5 | HR@3=0.1869, MAP@3=0.1366

  0%|          | 0/30 [00:00<?, ?it/s]

 76%|███████▌  | 73/96 [00:53<00:27,  1.19s/it]

factors=32, alpha=5, iterations=30, reg=0.01 | HR@3=0.1810, MAP@3=0.1329

  0%|          | 0/30 [00:00<?, ?it/s]

 77%|███████▋  | 74/96 [00:54<00:25,  1.16s/it]

factors=32, alpha=5, iterations=30, reg=0.05 | HR@3=0.1852, MAP@3=0.1372

  0%|          | 0/30 [00:00<?, ?it/s]

 78%|███████▊  | 75/96 [00:55<00:24,  1.16s/it]

factors=32, alpha=5, iterations=30, reg=0.1 | HR@3=0.1860, MAP@3=0.1385

  0%|          | 0/30 [00:00<?, ?it/s]

 79%|███████▉  | 76/96 [00:56<00:22,  1.12s/it]

factors=32, alpha=5, iterations=30, reg=0.5 | HR@3=0.1843, MAP@3=0.1389

  0%|          | 0/40 [00:00<?, ?it/s]

 80%|████████  | 77/96 [00:58<00:22,  1.19s/it]

factors=32, alpha=5, iterations=40, reg=0.01 | HR@3=0.1852, MAP@3=0.1347

  0%|          | 0/40 [00:00<?, ?it/s]

 81%|████████▏ | 78/96 [00:59<00:22,  1.24s/it]

factors=32, alpha=5, iterations=40, reg=0.05 | HR@3=0.1894, MAP@3=0.1389

  0%|          | 0/40 [00:00<?, ?it/s]

 82%|████████▏ | 79/96 [01:01<00:22,  1.31s/it]

factors=32, alpha=5, iterations=40, reg=0.1 | HR@3=0.1877, MAP@3=0.1364

  0%|          | 0/40 [00:00<?, ?it/s]

 83%|████████▎ | 80/96 [01:02<00:20,  1.29s/it]

factors=32, alpha=5, iterations=40, reg=0.5 | HR@3=0.1886, MAP@3=0.1371

  0%|          | 0/10 [00:00<?, ?it/s]

 84%|████████▍ | 81/96 [01:02<00:15,  1.05s/it]

factors=32, alpha=10, iterations=10, reg=0.01 | HR@3=0.1675, MAP@3=0.1153

  0%|          | 0/10 [00:00<?, ?it/s]

 85%|████████▌ | 82/96 [01:03<00:12,  1.13it/s]

factors=32, alpha=10, iterations=10, reg=0.05 | HR@3=0.1641, MAP@3=0.1136

  0%|          | 0/10 [00:00<?, ?it/s]

 86%|████████▋ | 83/96 [01:04<00:11,  1.14it/s]

factors=32, alpha=10, iterations=10, reg=0.1 | HR@3=0.1717, MAP@3=0.1166

  0%|          | 0/10 [00:00<?, ?it/s]

 88%|████████▊ | 84/96 [01:05<00:11,  1.09it/s]

factors=32, alpha=10, iterations=10, reg=0.5 | HR@3=0.1827, MAP@3=0.1278

  0%|          | 0/20 [00:00<?, ?it/s]

 89%|████████▊ | 85/96 [01:06<00:12,  1.15s/it]

factors=32, alpha=10, iterations=20, reg=0.01 | HR@3=0.1827, MAP@3=0.1306

  0%|          | 0/20 [00:00<?, ?it/s]

 90%|████████▉ | 86/96 [01:08<00:11,  1.13s/it]

factors=32, alpha=10, iterations=20, reg=0.05 | HR@3=0.1776, MAP@3=0.1281

  0%|          | 0/20 [00:00<?, ?it/s]

 91%|█████████ | 87/96 [01:08<00:09,  1.05s/it]

factors=32, alpha=10, iterations=20, reg=0.1 | HR@3=0.1776, MAP@3=0.1282

  0%|          | 0/20 [00:00<?, ?it/s]

 92%|█████████▏| 88/96 [01:09<00:07,  1.05it/s]

factors=32, alpha=10, iterations=20, reg=0.5 | HR@3=0.1776, MAP@3=0.1327

  0%|          | 0/30 [00:00<?, ?it/s]

 93%|█████████▎| 89/96 [01:10<00:06,  1.01it/s]

factors=32, alpha=10, iterations=30, reg=0.01 | HR@3=0.1818, MAP@3=0.1329

  0%|          | 0/30 [00:00<?, ?it/s]

 94%|█████████▍| 90/96 [01:11<00:05,  1.01it/s]

factors=32, alpha=10, iterations=30, reg=0.05 | HR@3=0.1759, MAP@3=0.1336

  0%|          | 0/30 [00:00<?, ?it/s]

 95%|█████████▍| 91/96 [01:12<00:05,  1.03s/it]

factors=32, alpha=10, iterations=30, reg=0.1 | HR@3=0.1785, MAP@3=0.1336

  0%|          | 0/30 [00:00<?, ?it/s]

 96%|█████████▌| 92/96 [01:13<00:04,  1.08s/it]

factors=32, alpha=10, iterations=30, reg=0.5 | HR@3=0.1810, MAP@3=0.1348

  0%|          | 0/40 [00:00<?, ?it/s]

 97%|█████████▋| 93/96 [01:15<00:03,  1.13s/it]

factors=32, alpha=10, iterations=40, reg=0.01 | HR@3=0.1843, MAP@3=0.1340

  0%|          | 0/40 [00:00<?, ?it/s]

 98%|█████████▊| 94/96 [01:16<00:02,  1.22s/it]

factors=32, alpha=10, iterations=40, reg=0.05 | HR@3=0.1843, MAP@3=0.1337

  0%|          | 0/40 [00:00<?, ?it/s]

 99%|█████████▉| 95/96 [01:18<00:01,  1.28s/it]

factors=32, alpha=10, iterations=40, reg=0.1 | HR@3=0.1818, MAP@3=0.1348

  0%|          | 0/40 [00:00<?, ?it/s]

100%|██████████| 96/96 [01:20<00:00,  1.19it/s]

factors=32, alpha=10, iterations=40, reg=0.5 | HR@3=0.1827, MAP@3=0.1362

Лучшие гиперпараметры:
   factors  alpha   reg  iterations      HR@3     MAP@3
0       16      1  0.05          30  0.255051  0.190937
1       16      1  0.10          30  0.254209  0.190376
2       16      1  0.01          30  0.259259  0.190095
3       16      1  0.50          30  0.257576  0.189254
4       16      1  0.50          10  0.250842  0.188692
5       16      1  0.10          40  0.255051  0.188552
6       16      1  0.01          20  0.250842  0.188412
7       16      1  0.01          40  0.255892  0.188131
8       16      1  0.10          10  0.254209  0.188131
9       16      1  0.50          20  0.251684  0.187991

In [ ]:
print("\nЛучшие гиперпараметры:")
print(results_df.head(1))

Лучшие гиперпараметры:
   factors  alpha   reg  iterations      HR@3     MAP@3
0       16      1  0.05          30  0.255051  0.190937

Итого HR@3 удалось повысить на 50%, а MAP@3 на 91%